server:
  port: 9000

spring:
  application:
    name: demo

  datasource:
    platform: mysql
    url: jdbc:mysql://lucia-db.c5yiv3rgxzzj.ap-northeast-2.rds.amazonaws.com/UmcDB?autoReconnect=true
    username: admin
    password: acejsy6190
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    # driver-class-name: com.mysql.jdbc.Driver # mysql 5버전